version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME:postgres
      - SPRING_DATASOURCE_PASSWORD:postgres
#    command: ["/app/wait-for-it.sh", "db:5432", "--", "java", "-jar", "app.jar"]
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata: